sudo: required
dist: trusty
language: node_js
branches:
  only:
  - source
node_js:
- 4.4.5
before_script:
- openssl aes-256-cbc -K $encrypted_fa34bcccd2fa_key -iv $encrypted_fa34bcccd2fa_iv 
  -in .travis.config.tgz.enc -out .travis.config.tgz -d
- tar -xzvf .travis.config.tgz
- ./scripts/setup.js --verbose
script:
- npm run build
after_success:
- chmod 600 .config/sshKey
- eval "$(ssh-agent -s)"
- ssh-add .config/sshKey
- git config --global user.email "travis-ci@waigojs.com"
- git config --global user.name "Travis CI"
- cd public
- git init
- git add .
- git commit -m "Deploy to Github Pages"
- npm run deploy
# - git push --force "git@github.com:waigo/waigo.github.io.git" master:master
notifications:
  slack:
    secure: "mzQUmiTt0iAK24eJEgDs2qOVD9ZeUvqw+hRh6rquouUIYJQsKcwbFdk4rKP4I6PFTQRrRVP9YxnxfdjSZzPDeGE5us5HWKQBYaAjSeHEdMEa+UXmdbxRtej3fvAZAWXRWq01k+d697fU+tS1rGbN467tAuXaBWFEWOuubGWBOlA="

