siteTitle="Waigo.js"
tagLine="Node.js ES6 framework for extendable, scalable back-ends."
linkPrefix = "/"
githubUrl = "https://github.com/waigo/waigo"
twitterId = "waigojs"
twitterUrl = "https://twitter.com/waigojs"
discussUrl = "https://discord.gg/Jf3pGjf"
docsLink = "/docs/Introduction/Motivation/"
gettingStartedLink = "/docs/GettingStarted/Requirements/"