siteTitle="Waigo.js"
tagLine="Node.js ES6 framework for reactive, data-driven apps and APIs"
linkPrefix = "/"
githubUrl = "https://github.com/waigo/waigo"
twitterId = "waigojs"
twitterUrl = "https://twitter.com/waigojs"
discussUrl = "https://discord.gg/Jf3pGjf"
docsLink = "/docs/introduction/motivation/"
apiLink = "/api/"
gettingStartedLink = "/docs/gettingstarted/requirements/"
apiBaseUrl = "/api"
githubDocsBaseUrl = "https://github.com/waigo/waigo/tree/master/docs"